name: Build and Test

on: [push, pull_request]

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Linux
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install pip --upgrade
          pip install wheel --upgrade
          pip install twine --upgrade
          pip install cpuid --upgrade
          # pip install conan --upgrade
          pip install setuptools --upgrade
        shell: bash

      - name: Settting EnvVars
        shell: bash
        run: |
          echo "UNIT_TESTS=true" >> $GITHUB_ENV
          echo "UPLOAD_PKG=true" >> $GITHUB_ENV

      - name: Build package
        shell: bash
        run: |
          set -e
          set -x
          python --version
          pip install -e .
          python setup.py sdist

      - name: Upload to PyPI
        if: github.ref == 'refs/heads/master'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true


# References:
  # https://github.com/radareorg/radare2